-- Create test patient user in Supabase
-- Step 1: Insert into auth.users table
INSERT INTO auth.users (
    id,
    instance_id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    phone,
    phone_confirmed_at,
    confirmation_sent_at,
    recovery_sent_at,
    email_change_sent_at,
    new_email,
    new_phone,
    invited_at,
    action_link,
    email_change,
    email_change_confirm_status,
    banned_until,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    created_at,
    updated_at,
    phone_change,
    phone_change_token,
    phone_change_sent_at,
    confirmed_at,
    email_change_token_current,
    email_change_token_new,
    recovery_token,
    reauthentication_token,
    reauthentication_sent_at,
    is_sso_user,
    deleted_at
) VALUES (
    gen_random_uuid(),
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    'testpatient@example.com',
    crypt('password123', gen_salt('bf')), -- Password: password123
    NOW(),
    '+2348106733459',
    NOW(),
    NOW(),
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    '{"provider": "email", "providers": ["email"]}',
    '{"full_name": "Test Patient", "role": "patient"}',
    false,
    NOW(),
    NOW(),
    NULL,
    NULL,
    NULL,
    NOW(),
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    NULL
);

-- Step 2: Insert into patient_registrations table
WITH new_user AS (
    SELECT id FROM auth.users WHERE email = 'testpatient@example.com' ORDER BY created_at DESC LIMIT 1
)
INSERT INTO patient_registrations (
    user_id,
    full_name,
    gender,
    age,
    phone_number,
    email,
    city,
    state,
    country,
    marital_status,
    emergency_contact_name,
    emergency_contact_phone,
    identification_type,
    identification_number
) 
SELECT 
    new_user.id,
    'Test Patient',
    'male',
    30,
    '+2348106733459',
    'testpatient@example.com',
    'Lagos',
    'Lagos',
    'Nigeria',
    'single',
    'Emergency Contact',
    '+2348111111111',
    'nin',
    '12345678901'
FROM new_user;